### ISSUE TITLE
Migrate away from mdtool and use xbuild for iOS

### ISSUE THREAD

**Issue by michaelstonis** [bitrise-io/xamarin-builder#20]
mdtool is mostly deprecated at this point. I believe calls to it are just wrappers for other xbuild calls. All Xamarin Unified API projects are using the msbuild/xbuild engine as well. It would be nice to have this an an option at least instead of just mdtool.

**Comment by birmacher** [comment]
We are currently validating the difference between mdtool and xbuild for iOS projects. We are waiting till the IDE will ignore the Custom Commands ( old format ) and when it happens it seems we can simply migrate to xbuild.

Till that point it can be that we will add the xbuild as a default option and let the users to use mdtool if needed.

**Comment by godrei** [comment]
Hi @michaelstonis 

The new xamarin-archive step is available in the steplib. It uses xbuild by default for iOS, macOS and tvOS project, also have an input to switch back to mdtool.

The blogpost about the new step and migration:
http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html
